#version: 0.2 
#
#phases: 
#  build: 
#    commands: 
#      - echo "Entering build phase..." 
#      - echo "Building Jar file with help of Maven" 
#      - ls 
#      - mvn clean install
#      - echo "Building docker image" 
#      - docker build -t praveenraja16/tweetapp:latest . 
#     
#  post_build: 
#    commands: 
#      - echo "Entered the post-build phase.." 
#      - echo "Pushing Docker Image" 
#      - docker push praveenraja16/tweetapp:latest 
#      - echo writing deifinition file 
#      - printf '[{"name":"tweetapp","imageUri":"%s"}]' praveenraja16/tweetapp:latest > imagedefinitions.json 
#artifacts: 
#  files: imagedefinitions.json

version: 0.2 

phases: 
  build:
    commands:
      - echo "ENTERING BUILD PHASE..."
      - mvn clean install -DskipTests
  
  post_build:
    commands:
      - echo "BUILD COMPLETED SUCCESSFULLY :)"
      
artifacts:
  files:
    - target/tweet-app.jar
  discard-paths: yes
      
