version: '3'

services:
  
  tweet-backend:
    build: .
    ports: 
      - 8000:8000
      
  zookeeper-server:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
    - "2181:2181"
  
  kafka-server:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
    - "9092:9092"
    depends_on:
      - zookeeper-server
    environment: 
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ZOOKEEPER_CONNECT: zookeeper-server:2181
      KAFKA_CREATE_TOPICS: "tweet"
      KAFKA_BROKER_ID: 1